Repository hasadna/anyway, pull requests merged in 2021-01, with the labels that each got.

#1648 User registration API
  alembic/versions/10023013f155_change_user_oauth_table_for_new_use_case.py
  anyway/current_user_functions.py
  anyway/error_code_and_strings.py
  anyway/flask_app.py
  anyway/models.py
  anyway/oauth.py
  anyway/utilities.py
  requirements.txt
  tests/test_flask.py
  tests/test_utilities.py
Labels: backend

#1674 Add urls of anyway-infographics
  anyway/backend_constants.py
  anyway/utilities.py
  tests/test_utilities.py
Labels: backend, frontend

#1673 User registration API (#1648)
  alembic/versions/10023013f155_change_user_oauth_table_for_new_use_case.py
  anyway/backend_constants.py
  anyway/current_user_functions.py
  anyway/error_code_and_strings.py
  anyway/flask_app.py
  anyway/models.py
  anyway/oauth.py
  anyway/utilities.py
  requirements.txt
  tests/test_flask.py
  tests/test_utilities.py
Labels: backend, frontend

#1675 Change injured_count_per_age_group by issue #1645 + Translation
  anyway/backend_constants.py
  anyway/infographics_dictionaries.py
  anyway/infographics_utils.py
  anyway/utilities.py
  messages.pot
  translations/en/LC_MESSAGES/messages.mo
  translations/en/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.mo
  translations/he/LC_MESSAGES/messages.po
Labels: backend, enhancement

#1678 1592: Localize head on collisions comparison
  anyway/infographics_utils.py
  messages.pot
  translations/en/LC_MESSAGES/messages.mo
  translations/en/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.mo
  translations/he/LC_MESSAGES/messages.po
Labels: 1 - Ready

#1679 Add get user info API
  anyway/current_user_functions.py
  anyway/flask_app.py
  tests/test_flask.py
Labels: backend, enhancement

#1684 Add User API docs
  docs/USERAPI.md
Labels: backend
